services:
  rabbitmq:
    image: rabbitmq:3-management # ui
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  producer:
    container_name: messages_producer
    build:
      context: ./seed
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
